# Site settings
title: Redundant Mechatronic Lab
email: redundantlab@pm.me
description: Make stuff of your dreams into the reality. We help compose them.

# Use correct baseurl
baseurl: "/Redundant_Mechatronic_Lab"  # Change this to match GitHub Pages repository name
url: "https://chetanpm.github.io"      # GitHub Pages main domain

# Ensure Jekyll includes the _pages directory
include:
  - _pages

# Define pages collection correctly
collections:
  pages:
    output: true

# Set permalink structure to avoid conflicts
permalink: pretty  # Ensures pages generate clean URLs like /thank-you/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#007DAC'

# Social networks usernames
social:
  - title: twitter
    url: https://twitter.com/pmchetan
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/chetanpm/redundantlab

# Build settings
markdown: kramdown
paginate: 5  # Optional: Set pagination for blog posts
paginate_path: "/page:num/"

# Plugins (Optional, but useful)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag