# Site settings
title: Redundant Mechatronic Lab
email: redundantlab@pm.me
description: Make stuff of your dreams into the reality. We help compose them.
# Use correct baseurl
baseurl: "/Redundant_Mechatronic_Lab" # Change this to match GitHub Pages URL
url: "https://chetanpm.github.io"    # GitHub Pages main domain
# Ensure Jekyll includes the _pages directory
include:
  - _pages
# Ensure pages are generated
collections:
  pages:
    output: true
    permalink: /:path/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#007DAC'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pmchetan
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/chetanpm/redundantlab

# Build settings
markdown: kramdown
permalink: pretty