# Site settings
title: Redundant Mechatronic Lab
email: redundantlab@pm.me
description: Make stuff of your dreams into the reality. We help compose them.
baseurl: /redundantlab
url: "https://redundantlab.in" # the base hostname & protocol for your site

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#007DAC'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pmchetan
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/chetanpm/redundantlab

# Build settings
markdown: kramdown
permalink: pretty

# ✅ Ensure Jekyll includes the _pages directory
include:
  - _pages